name: .NET Core

on:
  push:
    branches: [ marceloaugusto80-dev-pipeline ]
  pull_request:
    types: [closed]
    branches: [ marceloaugusto80-dev-pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: CSRequest/CSRequest.csproj
        VERSION_FILE_PATH: version
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        
    
